### ISSUE TITLE
Add Merge Sort Code

### ISSUE THREAD

**Issue by nitind2411** [nitind2411/hacktoberfest-2022-DSA-CP#1]

**Comment by dnitin24** [comment]
Hello Sir, Please Assign this issue to me

**Comment by nitind2411** [comment]
assigned to @dnitin24

**Comment by nitind2411** [comment]
assign to @dnitin24 issue #1

**Comment by Saaraansh10** [comment]
can you please assign this issue to me @nitind2411 ?

**Comment by Avy2808** [comment]
Hey can you please assign this issue to me? @nitind2411

**Comment by falguni300103** [comment]
can you please assign this issue to me ? @nitind2411

**Comment by nitind2411** [comment]
Hello @falguni300103  @Saaraansh10  @Avy2808 Thanks for showing your interest but this issue already have been resolved, Please try to create new issue, or attach new DSA
