### ISSUE TITLE
Add 0-1 knapsack 

### ISSUE THREAD

**Issue by Dhiman2020** [nitind2411/hacktoberfest-2022-DSA-CP#17]
I want to contribute this code please assign this to me.

**Comment by nitind2411** [comment]
Assigned to @Dhiman2020 issue no. #17

**Comment by nitind2411** [comment]
> I want to contribute this code please assign this to me.

Assigned to @Dhiman2020

**Comment by nitind2411** [comment]
@Dhiman2020 assigned to you, Make a Pull Request for the same

**Comment by Saaraansh10** [comment]
Can you please assign this issue to me @nitind2411 ?

**Comment by Avy2808** [comment]
Hey can you please assign this issue to me? @nitind2411

**Comment by nitind2411** [comment]
This issue has been resolved, Try to create new issue or make new PR @falguni300103 @Saaraansh10 @Avy2808
