### ISSUE TITLE
Add Basic programs for using a Linked List

### ISSUE THREAD

**Issue by arya312** [nitind2411/hacktoberfest-2022-DSA-CP#22]
I have made 4 pull requests for basic programs of Linked List. Do check them out and merge them if they satisfy the criteria of this repository.

Sources of these codes are from geeksforgeeks.com

Thanks!

**Comment by nitind2411** [comment]
Please try to merge searching and finding length into a same code as they both the codes are just traversing the linked list

**Comment by ujwxl23** [comment]
Hello, can u assign me this issue for hacktoberfest. I can contribute by adding insertion, deletion, searching, sorting the linked-list. Also, a programs on circular linked-list.

**Comment by ujwxl23** [comment]
@nitind2411

**Comment by Saaraansh10** [comment]
Can you please assign this issue to me @nitind2411 ?

**Comment by Avy2808** [comment]
Hey can you please assign this issue to me? @nitind2411

**Comment by nitind2411** [comment]
Assigned to @ujwxl23

**Comment by nitind2411** [comment]
Hello @Saaraansh10 , Thanks for showing your interest but its already get assigned to @ujwxl23 firstly so Please create a new issue , that consist of new data structure or algorithm

**Comment by nitind2411** [comment]
Hello @falguni300103  , Thanks for showing your interest but its already get assigned to @ujwxl23 firstly so Please create a new issue , that consist of new data structure or algorithm

**Comment by nitind2411** [comment]
Hello @Avy2808  , Thanks for showing your interest but its already get assigned to @ujwxl23 firstly so Please create a new issue , that consist of new data structure or algorithm

**Comment by nitind2411** [comment]
Try to Contribute as soon as possible @falguni300103 @Saaraansh10 @Avy2808 , Assigned to you

**Comment by Saaraansh10** [comment]
> Try to Contribute as soon as possible @falguni300103 @Saaraansh10 @Avy2808 @ujwxl23 , Assigned to you

Code written and pull request made

**Comment by nitind2411** [comment]
I have merged you PR @Saaraansh10 
Thanks for Contributing

**Comment by ujwxl23** [comment]
@nitind2411 I have created 2 PRs for linkedlist with all operations and a circular linkedlist. 
Please accept this under hacktoberfest 2022.
Thank u!!
